version: '3.7'

services:
  web-metas:
    image: nginx:stable-alpine3.19-slim
    container_name: web-metas
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-metas
    networks:
      - red-gane-int

  api-metas:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-metas
    image: api-metas:v1.0
    networks:
      - red-gane-int
    environment:
      - TZ=America/Bogota

networks:
  red-gane-int:
    external: true
    